// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://axrwpxoszbylchsrbsqn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF4cndweG9zemJ5bGNoc3Jic3FuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMTQ3MDgsImV4cCI6MjA2NDY5MDcwOH0.dUTHM7ojOOj7Ziagc8JbAB1GKNORDpE6WjUNLWj0crw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);